src/main/java/com/multi/hereevent/member/MemberController.java
src/main/java/com/multi/hereevent/member/MemberDAOImpl.java
src/main/java/com/multi/hereevent/member/MemberServiceImpl.java
src/main/resources/mapper/member.xml
src/main/resources/static/common/css/login.css
src/main/resources/static/common/css/register.css
src/main/resources/static/index.html
src/main/resources/templates/login/login.html
src/main/resources/templates/login/register.html
src/main/resources/templates/template/footer.html
src/main/resources/templates/template/header.html
src/main/resources/templates/template/mainLayout.html

login,member_insert,layout

---

src/main/java/com/multi/hereevent/member/MemberController.java
src/main/java/com/multi/hereevent/member/MemberDAO.java
src/main/java/com/multi/hereevent/member/MemberDAOImpl.java
src/main/java/com/multi/hereevent/member/MemberService.java
src/main/java/com/multi/hereevent/member/MemberServiceImpl.java
src/main/resources/application.properties
src/main/resources/mapper/member.xml
src/main/resources/static/common/css/mypage.css
src/main/resources/templates/common/error_page.html
src/main/resources/templates/layout/footer.html
src/main/resources/templates/layout/header.html
src/main/resources/templates/layout/mainLayout.html
src/main/resources/templates/mypage/edit_birth.html
src/main/resources/templates/mypage/edit_nick.html
src/main/resources/templates/mypage/myevent.html
src/main/resources/templates/mypage/myinterest.html
src/main/resources/templates/mypage/mypage.html
src/main/resources/templates/mypage/myreview.html

feat: 마이페이지

---

src/main/java/com/multi/hereevent/map/MapController.java
src/main/resources/application.properties
src/main/resources/templates/kakaomap/kakaomap.html

kakao map api 이미지 지도와 마커 추가만 했습니다.

feat : kakaomap api 추가

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/resources/static/common/css/detailedPage.css
src/main/resources/static/common/js/main.js
src/main/resources/templates/detailedPage/detailedPage.html
src/main/resources/templates/main/main.html

feat: 메인페이지 html css 생성(main.html, newMain.css=>css는 급하게 분리한거라 에러 많아서… 같이 커밋하지 않고 파일로 따로 올리겠습니다)
refactor: detailedPage, main.js  ajax만지면서 수정한건데 자잘한 코드변화만 있고 내용변화x
design: 자잘한 디자인 변경

detailedPage, mainPage수정

---

src/main/java/com/multi/hereevent/event/crawling/CrawlingService.java
src/main/java/com/multi/hereevent/fileupload/FileUploadService.java
src/main/resources/templates/detailedPage/detailedPage.html
src/main/resources/templates/mypage/editProfileImg.html
src/main/resources/templates/mypage/mypage.html

이미지 url 잘못된 경우 오류 처리
이미지 저장 경로 변경
hereevent_upload/event 폴더 생성 필요

feat: popup crawling

---

src/main/java/com/multi/hereevent/dto/EventDTO.java
src/main/java/com/multi/hereevent/dto/ReservationDTO.java
src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/EventDAO.java
src/main/java/com/multi/hereevent/event/EventDAOImpl.java
src/main/java/com/multi/hereevent/event/EventService.java
src/main/java/com/multi/hereevent/event/EventServiceImpl.java
src/main/resources/mapper/event.xml
src/main/resources/mapper/member.xml
src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/event/eventCategoryList.html
src/main/resources/templates/main/mainPage2.html

-별점순 목록
-예약 기능
-예약 페이지html 대충 제작

별점순 목록, 예약 기능 제작

---

src/main/java/com/multi/hereevent/map/MapController.java
src/main/java/com/multi/hereevent/map/MapDAO.java
src/main/java/com/multi/hereevent/map/MapDAOImpl.java
src/main/java/com/multi/hereevent/map/MapService.java
src/main/java/com/multi/hereevent/map/MapServiceImpl.java
src/main/resources/mapper/map.xml
src/main/resources/templates/kakaomap/clicktest.html
src/main/resources/templates/main/bootTest.html
src/main/resources/templates/main/mainPage.html

map_clickTest~ing

---

src/main/java/com/multi/hereevent/dto/EventDTO.java
src/main/java/com/multi/hereevent/event/EventDAO.java
src/main/java/com/multi/hereevent/event/EventDAOImpl.java
src/main/java/com/multi/hereevent/event/EventService.java
src/main/java/com/multi/hereevent/event/EventServiceImpl.java
src/main/java/com/multi/hereevent/event/crawling/CrawlingService.java
src/main/resources/mapper/event.xml

크롤링 할 때마다 같은 팝업이어도 이미지 저장되는 거 해결
홈페이지, sns 링크 못 가져오는 부분 제거
크롤링 시 변경된 부분이 있는 경우 새롭게 추가되므로 이름과 기간만 같아도 insert 되지 않도록 변경

fix: 이미지 중복 저장 해결, 링크 정보 제거

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/EventService.java
src/main/resources/mapper/event.xml
src/main/resources/static/common/css/login.css
src/main/resources/static/common/css/register.css
src/main/resources/templates/login/login.html
src/main/resources/templates/main/mainPage2.html

login, register, css수정
- header, footer 추가
- 가운데정렬

login, register, css수정

---

src/main/java/com/multi/hereevent/dto/ButtonDTO.java
src/main/java/com/multi/hereevent/map/MapController.java
src/main/java/com/multi/hereevent/map/MapDAO.java
src/main/java/com/multi/hereevent/map/MapDAOImpl.java
src/main/java/com/multi/hereevent/map/MapService.java
src/main/java/com/multi/hereevent/map/MapServiceImpl.java
src/main/resources/mapper/map.xml
src/main/resources/static/index.html
src/main/resources/templates/kakaomap/clicktest.html

- 지도 위치이동 js코드 수정

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/resources/static/common/css/detailedPage.css
src/main/resources/templates/detailedPage/navigation.html
src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/kakaomap/kakaomap.html

navigation.html에 지도 추가 후 각 행사의 주소로 지도 중심 좌표 맞춰놨습니다. 그 주변 편의점, 식당 등 확인 가능하도록 추가했습니다.

Navigation

---

src/main/java/com/multi/hereevent/map/MapController.java
src/main/java/com/multi/hereevent/map/MapDAO.java
src/main/java/com/multi/hereevent/map/MapDAOImpl.java
src/main/java/com/multi/hereevent/map/MapService.java
src/main/java/com/multi/hereevent/map/MapServiceImpl.java
src/main/resources/mapper/map.xml
src/main/resources/templates/kakaomap/clicktest.html

- 지도 마커 js코드 정리 및 데이터 연결, 프론트 남음

- 지도 컨트롤러-목록출력 완료

---

src/main/resources/templates/kakaomap/clicktest.html

- 프론트 작업, 데이터 연결이슈(지도에 표시되는 팝업과 하단 목록표시 연결 등) 몇개 해결해야함

- 지도 마커 js코드 정리 및 데이터 연결

---

src/main/resources/static/common/css/detailedPage.css
src/main/resources/templates/detailedPage/reservation.html

design: detailedPage.css 수정(달력 크기 및 코드 수정)

design: detailedPage.css 수정(달력 크기 및 코드 수정)

---

src/main/java/com/multi/hereevent/category/CategoryDAO.java
src/main/java/com/multi/hereevent/category/CategoryDAOImpl.java
src/main/java/com/multi/hereevent/category/CategoryService.java
src/main/java/com/multi/hereevent/category/CategoryServiceImpl.java
src/main/java/com/multi/hereevent/dto/FourEventByCategoryDTO.java
src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/EventDAO.java
src/main/java/com/multi/hereevent/event/EventDAOImpl.java
src/main/java/com/multi/hereevent/event/EventService.java
src/main/java/com/multi/hereevent/event/EventServiceImpl.java
src/main/resources/mapper/category.xml
src/main/resources/mapper/event.xml
src/main/resources/templates/main/mainPage.html

- 카테고리별 조회 수정,4개씩 출력 기능 완성 (css 보완 필요)

- 카테고리별 조회 수정,4개씩 출력 기능 완성 (css 보완 필요)

---

src/main/java/com/multi/hereevent/dto/EventDTO.java
src/main/java/com/multi/hereevent/wait/WaitController.java
src/main/java/com/multi/hereevent/wait/WaitDAO.java
src/main/java/com/multi/hereevent/wait/WaitDAOImpl.java
src/main/java/com/multi/hereevent/wait/WaitService.java
src/main/java/com/multi/hereevent/wait/WaitServiceImpl.java
src/main/resources/mapper/wait.xml
src/main/resources/templates/waitPage/mywait.html
src/main/resources/templates/waitPage/waitlogin.html

feat: 대기 로그인 오류 시 오류 팝업 뜨도록 설정 refactor: 입장가능시간 null값에서 값 나오도록 수정 (이과정에서 eventDTO의 wait_limit에 임의로 값부여)

대기 등록, 로그인, 나의 대기 페이지 1차 완성

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/member/MemberController.java
src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/layout/header.html

-logout 추가,reservation 수정

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/time/EventTimeDAO.java
src/main/java/com/multi/hereevent/event/time/EventTimeDAOImpl.java
src/main/java/com/multi/hereevent/event/time/EventTimeService.java
src/main/java/com/multi/hereevent/event/time/EventTimeServiceimpl.java
src/main/resources/mapper/eventTime.xml
src/main/resources/templates/detailedPage/reservation.html

-reservation time 수정

---

src/main/java/com/multi/hereevent/map/MapController.java
src/main/resources/mapper/map.xml
src/main/resources/static/common/css/map.css
src/main/resources/templates/kakaomap/clicktest.html

- 마커 데이터연결

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/time/EventTimeServiceimpl.java
src/main/resources/application.properties
src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/event/eventCategoryList.html

-reservation 달력 수정

---

src/main/java/com/multi/hereevent/map/MapController.java
src/main/java/com/multi/hereevent/review/ReviewController.java
src/main/resources/application.properties
src/main/resources/templates/admin/review.html
src/main/resources/templates/kakaomap/clicktest.html

- 지도 버튼누른데이터- 마커데이터 연결

---

src/main/java/com/multi/hereevent/map/MapDAO.java
src/main/java/com/multi/hereevent/map/MapDAOImpl.java
src/main/java/com/multi/hereevent/map/MapService.java
src/main/java/com/multi/hereevent/map/MapServiceImpl.java
src/main/java/com/multi/hereevent/review/ReviewController.java
src/main/resources/application.properties
src/main/resources/mapper/map.xml
src/main/resources/templates/admin/review.html

- 리뷰 사진이랑 행사이름누르면 상세페이지로 이동하는 링크

- 맵 필요없는 메소드삭제

---

src/main/java/com/multi/hereevent/member/MemberController.java
src/main/resources/application.properties
src/main/resources/static/common/css/login.css
src/main/resources/static/common/css/register.css
src/main/resources/templates/login/register.html

-로그인 버튼 색상 통일
-회원가입(비밀번호 확인기능)

-회원가입(비밀번호 확인기능), 로그인 버튼 색상 통일

---

src/main/java/com/multi/hereevent/dto/EventDTO.java
src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/EventDAO.java
src/main/java/com/multi/hereevent/event/EventDAOImpl.java
src/main/java/com/multi/hereevent/event/EventService.java
src/main/java/com/multi/hereevent/event/EventServiceImpl.java
src/main/java/com/multi/hereevent/fileupload/FileUploadService.java
src/main/java/com/multi/hereevent/member/MemberController.java
src/main/resources/mapper/event.xml
src/main/resources/mapper/member.xml
src/main/resources/static/common/css/admin.css
src/main/resources/static/common/css/insertEvent.css
src/main/resources/static/common/js/adminEvent.js
src/main/resources/templates/admin/event.html
src/main/resources/templates/event/insert.html
src/main/resources/templates/login/register.html

이벤트 관리 페이지 작업, 이벤트 등록, 회원가입 프로필사진 수정

이벤트 관리 작업, 회원가입 프로필사진 수정

---

src/main/java/com/multi/hereevent/event/EventController.java
src/main/resources/application.properties
src/main/resources/templates/detailedPage/detailedPage.html
src/main/resources/templates/main/mainPage.html
src/main/resources/templates/waitPage/mywait.html

fix: 대기페이지 입장, 취소 눌렀을때 팝업으로 입장, 취소되었습니다 안나오던 것 수정

design: 상세페이지 탭 눌렀을때 누른 곳 강조 표시 되도록 수정

---

src/main/java/com/multi/hereevent/member/MemberController.java
src/main/java/com/multi/hereevent/review/ReviewController.java
src/main/java/com/multi/hereevent/review/ReviewDAO.java
src/main/java/com/multi/hereevent/review/ReviewDAOImpl.java
src/main/java/com/multi/hereevent/review/ReviewService.java
src/main/java/com/multi/hereevent/review/ReviewServiceImpl.java
src/main/resources/application.properties
src/main/resources/mapper/review.xml
src/main/resources/static/common/js/admin.js
src/main/resources/templates/admin/review.html
src/main/resources/templates/login/interestCategory.html
src/main/resources/templates/login/register.html

회원가입시 생년월일 null 허용, 리뷰 선택삭제 기능 추가

fix: 회원가입시 생년월일 null 허용,  feat: 리뷰 선택삭제 기능 추가

---

src/main/java/com/multi/hereevent/dto/EventDTO.java
src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/mail/MailService.java

feat: 예약 등록 메일 전송 기능 구현

---

src/main/resources/static/common/css/admin.css
src/main/resources/static/common/css/main.css
src/main/resources/templates/detailedPage/review.html
src/main/resources/templates/login/login.html
src/main/resources/templates/login/register.html

상세페이지 영어 수정완료
로그인, 회원가입 상단바 적용

design: 프로필이미지 동그라미로

---

src/main/resources/static/common/css/detailedPage.css
src/main/resources/static/common/css/main.css
src/main/resources/templates/detailedPage/detailedPage.html
src/main/resources/templates/detailedPage/navigation.html
src/main/resources/templates/main/mainPage.html

design: 메인페이지 MARGIN추가 전체이벤트 버튼으로 대체 길찾기 수정

---

src/main/java/com/multi/hereevent/member/KakaoLoginController.java

카카오 로그인 url 수정

---

src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/mypage/myevent.html

예약 날짜를 3일 뒤부터 할 수 있도록 변경

---

src/main/java/com/multi/hereevent/reserve/ReserveDAO.java
src/main/java/com/multi/hereevent/reserve/ReserveDAOImpl.java
src/main/java/com/multi/hereevent/reserve/ReserveServiceImpl.java

예약 인원 제한 수정

---

src/main/java/com/multi/hereevent/admin/AdminController.java
src/main/java/com/multi/hereevent/event/EventController.java
src/main/java/com/multi/hereevent/event/EventServiceImpl.java
src/main/java/com/multi/hereevent/event/time/EventTimeServiceImpl.java
src/main/java/com/multi/hereevent/map/MapController.java
src/main/java/com/multi/hereevent/member/KakaoLoginController.java
src/main/java/com/multi/hereevent/member/MemberController.java
src/main/java/com/multi/hereevent/reserve/ReserveController.java
src/main/java/com/multi/hereevent/reserve/ReserveDAO.java
src/main/java/com/multi/hereevent/reserve/ReserveDAOImpl.java
src/main/java/com/multi/hereevent/reserve/ReserveService.java
src/main/java/com/multi/hereevent/reserve/ReserveServiceImpl.java
src/main/java/com/multi/hereevent/wait/WaitController.java
src/main/java/com/multi/hereevent/wait/WaitServiceImpl.java
src/main/resources/mapper/reserve.xml
src/main/resources/mapper/wait.xml
src/main/resources/templates/detailedPage/detailedPage.html
src/main/resources/templates/detailedPage/reservation.html
src/main/resources/templates/main/mainPage.html
src/main/resources/templates/mypage/myevent.html

sysout으로 찍히던 부분들 log.info로 찍히도록 수정

fix: email 예약 연동, wait 마이페이지에서 이동하는 부분 수정, reserve 안내문구 추가

---

src/main/resources/mapper/event.xml

fix: event mapper

---

src/main/java/com/multi/hereevent/event/time/EventTimeServiceImpl.java
src/main/java/com/multi/hereevent/reserve/ReserveDAO.java
src/main/java/com/multi/hereevent/reserve/ReserveDAOImpl.java
src/main/java/com/multi/hereevent/reserve/ReserveServiceImpl.java
src/main/resources/mapper/reserve.xml
src/main/resources/templates/detailedPage/reservation.html

같은 날짜, 같은 시간에 중복으로 예약되는 거 안 되도록 수정

feat: 중복 예약 수정

---

src/main/java/com/multi/hereevent/admin/AdminController.java
src/main/java/com/multi/hereevent/dto/ReserveDTO.java
src/main/java/com/multi/hereevent/reserve/ReserveDAO.java
src/main/java/com/multi/hereevent/reserve/ReserveDAOImpl.java
src/main/java/com/multi/hereevent/reserve/ReserveService.java
src/main/java/com/multi/hereevent/reserve/ReserveServiceImpl.java
src/main/resources/application.properties
src/main/resources/mapper/reserve.xml
src/main/resources/templates/admin/home.html
src/main/resources/templates/admin/reserve.html

admin_Reserve 추가
- 예약상태 reserve인 것만 조회하기 안됨
- 취소 눌렀을때 state : cancel로 update는 됨
- 체크박스로 일괄 취소 오류

feat: admin_Reserve 추가

---

src/main/java/com/multi/hereevent/admin/AdminController.java
src/main/resources/application.properties
src/main/resources/mapper/event.xml
src/main/resources/templates/event/update.html

- 이벤트 수정시 카테고리, 운영시간, 예약 인원, 대기 인원 데이터 출력 수정

fix: admin(event update)

---

src/main/java/com/multi/hereevent/admin/AdminController.java
src/main/resources/templates/event/update.html

- 이벤트 사진 입력 필수 항목 제외
- 사진 미변경 후 수정 버튼 클릭시, 사진 사라지는 오류 수정

fix: admin(event update 2)

---

src/main/resources/templates/event/update.html

fix: admin(event type 데이터 넘어가게)

fix: admin(event type 데이터 넘어가게)
